// Get DATA
export const START_GET_DATA = "START_GET_DATA";
export const ERROR = "ERROR";
export const CANCEL_ERROR = "CANCEL_ERROR";
export const GET_SUCCESS_DEFAULT_PRODUCTS = "GET_SUCCESS_DEFAULT_PRODUCTS";
export const GET_SUCCESS_STORE_PRODUCTS = "GET_SUCCESS_STORE_PRODUCTS";
export const GET_SUCCESS_NAME_PRODUCTS = "GET_SUCCESS_NAME_PRODUCTS";
export const GET_SUCCESS_NEW_PRODUCTS = "GET_SUCCESS_NEW_PRODUCTS";
export const GET_SUCCESS_REFER_PRODUCTS = "GET_SUCCESS_REFER_PRODUCTS";
export const FINISHALL = 'FINISHALL';
//cart
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_TO_CART = "REMOVE_PRODUCT_TO_CART";
export const INCR_QUANTITY = "INCR_QUANTITY";
export const DECR_QUANTITY = "DECR_QUANTITY";
export const TOTAL_MONEY = "TOTAL_MONEY";
export const GET_CART = "GET_CART"



