export const START_GET_DATA = "START_GET_DATA";
export const ERROR = "ERROR";
export const CANCEL_ERROR = "CANCEL_ERROR";
export const GET_SUCCESS_DEFAULT_PRODUCTS = "GET_SUCCESS_DEFAULT_PRODUCTS";
export const GET_SUCCESS_STORE_PRODUCTS = "GET_SUCCESS_STORE_PRODUCTS";
export const GET_SUCCESS_NAME_PRODUCTS = "GET_SUCCESS_NAME_PRODUCTS";
export const GET_SUCCESS_NEW_PRODUCTS = "GET_SUCCESS_NEW_PRODUCTS";
export const GET_SUCCESS_REFER_PRODUCTS = "GET_SUCCESS_REFER_PRODUCTS";
export const FINISHALL = 'FINISHALL'


