# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'Shopping' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Shopping
  platform :ios, '8.0'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  #pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
  #pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'
  #pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'



 target 'Shopping-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShoppingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

